config/routes.rb
require "constraints/subdomain_constraint"

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions", invitations: "users/invitations" }
  resources :home
  resources :sites

  constraints(SubdomainConstraint.new) do
    root "sites#show", as: :site_root
    resources :site_users, only: [ :destory ] do
      collection do
        post :invite
      end
    end
    resources :users, only: [ :index, :show, :edit, :update ]
  end

  root "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :set_completed_registration_false
  after_invitation_accepted :set_completed_registration_true

  belongs_to :site, optional: true
  has_many :site_users
  has_one_attached :avatar do |attachable|
    attachable.variant :avatar, resize_to_limit: [ 200, 200 ]
    attachable.variant :thumb, resize_to_limit: [ 50, 50 ]
  end

  validates :first_name, presence: true
  validates :last_name, presence: true

  ransacker :full_name do |parent|
    Arel::Nodes::NamedFunction.new("concat", [
      parent.table[:first_name],
      Arel::Nodes::Quoted.new(" "),
      parent.table[:last_name]
    ])
  end

  def self.ransackable_attributes(auth_object = nil)
    [ "full_name", "first_name", "last_name", "country", "email" ]
  end

  def self.ransackable_associations(auth_object = nil)
    [ "site_users" ]
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name

    "Anonymous"
  end

  def full_address
    "#{address}, #{zip_code}, #{city},"
  end

  private

  def set_completed_registration_false
    self.update(completed_registration: false)
  end

  def set_completed_registration_true
    self.update(completed_registration: true)
  end
end

app/controllers/Users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/Users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  before_action :set_current_site

  def create
    self.resource = invite_resource
    resource_invited = resource.errors.empty?

    yield resource if block_given?

    if resource_invited
      @users = @current_site.users

      if is_flashing_format? && self.resource.invitation_sent_at
        set_flash_message :notice, :send_instructions, email: self.resource.email
      end

      resource.site_users.find_or_create_by(site: @current_site, roles: :member)

      respond_to do |format|
        if self.method(:after_invite_path_for).arity == 1
          location = after_invite_path_for(current_inviter)
        else
          location = after_invite_path_for(current_inviter, resource)
        end

        format.html { respond_with resource, location: location }

        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.prepend("users", partial: "users/index/user_row", locals: { user: resource }),
            turbo_stream.update("flash", partial: "layouts/flash")
          ]
        end
      end
    else
      respond_with(resource)
    end
  end

  # PUT /resource/invitation
  def update
    raw_invitation_token = update_resource_params[:invitation_token]
    self.resource = accept_resource
    invitation_accepted = resource.errors.empty?

    yield resource if block_given?

    if invitation_accepted
      if resource.class.allow_insecure_sign_in_after_accept
        flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
        set_flash_message :notice, flash_message if is_flashing_format?
        resource.after_database_authentication
        sign_in(resource_name, resource)
        redirect_to site_root_url(subdomain: current_user.site_users.first.site.subdomain), allow_other_host: true
      else
        set_flash_message :notice, :updated_not_active if is_flashing_format?
        respond_with resource, location: new_session_path(resource_name)
      end
    else
      resource.invitation_token = raw_invitation_token
      respond_with(resource)
    end
  end
end

app/controllers/Users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/Users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/Users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
    new_site_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/Users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    redirect_to site_root_url(subdomain: current_user.site_users.first.site.subdomain), allow_other_host: true
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # Changed redirect_to for cleaning subdomain
  def respond_to_on_destroy
    respond_to do |format|
      format.all { head :no_content }
      format.any(*navigational_formats) { redirect_to root_url(subdomain: nil), status: Devise.responder.redirect_status, allow_other_host:  true }
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/Users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [ :show, :edit, :update ]
  before_action :set_current_site

  def index
    @q = @current_site.users.order(first_name: :asc).ransack(params[:q])
    @pagy, @users = pagy(@q.result.includes(:site_users), limit: 10)
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User was updated successfully"
      redirect_to user_url(subdomain: @user.site_users.first.site.subdomain), allow_other_host: true
    else
      render edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :phone_number,
                                 :country,
                                 :city,
                                 :zip_code,
                                 :address,
                                 :birthday,
                                 :languages,
                                 :education,
                                 :work_history,
                                 :about_me,
                                 :hobbies,
                                 :skills)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index/_user_row.html.erb
<tr class="border-b dark:border-gray-700">
  <td scope="row" class="px-10 py-3 font-medium text-gray-900 sm:px-5 whitespace-nowrap dark:text-white">
    <div class="flex items-center justify-start sm:justify-start">

      <% if user.avatar.present? %>
        <%= image_tag user.avatar.variant(:thumb), class:"rounded-full mr-4" %>
      <% else %>
        <%= image_tag("https://via.placeholder.com/50", class:"rounded-full mr-4", alt: "User avatar")%>
      <% end %>


      <div class="grid grid-rows-2">
        <div class="row-start-1">
          <%= highlight user.full_name, params.dig(:q, :full_name_or_country_or_site_users_roles_or_email_cont)%>
        </div>
        <div class="text-gray-400">
          <%= highlight user.email, params.dig(:q, :full_name_or_country_or_site_users_roles_or_email_cont) %> 
        </div>
      </div>
    </div>
  </td>
  <td class="px-5 py-3 sm:px-10"><%= highlight user.site_users.first.roles, params.dig(:q, :full_name_or_country_or_site_users_roles_or_email_cont)%></td>
  <td class="px-5 py-3 sm:px-10"><%= highlight user.country, params.dig(:q, :full_name_or_country_or_site_users_roles_or_email_cont)%></td>
  <td class="px-5 py-3 sm:px-10 itemst-center">
    <div class="flex items-center justify-center">
      <%= link_to 'Show', user_path(user), data: {turbo_frame: "_top"}, class:"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" %>
      <%= link_to 'Edit', edit_user_path(user), data: {turbo_frame: "_top"}, class:"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" %>
    </div>
  </td>
</tr>

app/views/users/index/_users_table.html.erb
<div class="p-3 bg-gray-50 dark:bg-gray-900 sm:p-5">
  <div class="max-w-screen-xl px-4 mx-auto lg:px-12">
    <div class="relative bg-white shadow-md dark:bg-gray-800 sm:rounded-lg">
      
      <div class="flex flex-col items-center justify-between p-4 space-y-3 md:flex-row md:space-y-0 md:space-x-4">
        <div class="w-full md:w-1/2">
          <%= search_form_for @q, data: {turbo_frame: :users_results, turbo_action: 'advance'} do |f| %>
            <%= f.label :full_name_or_country_or_site_users_roles_or_email_cont, class:"sr-only" %>
            <div class="relative">
              <%= f.search_field :full_name_or_country_or_site_users_roles_or_email_cont, 
                oninput: 'this.form.requestSubmit();', 
                class:"block w-full p-2 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500",
                placeholder: "Search for users" %>

              <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                <%= icon('fa-solid fa-magnifying-glass text-gray-400', '') %>
              </div>
            </div>
          <% end %>
        </div>
        
        <div class="flex flex-col items-stretch justify-end flex-shrink-0 w-full space-y-2 md:w-auto md:flex-row md:space-y-0 md:items-center md:space-x-3">
          <div data-controller="dialog" data-action="click->dialog#clickOutside" >
            <%= link_to "Add User", new_user_invitation_url(subdomain: @current_site.subdomain), data: {action: "click->dialog#open", turbo_frame: :modal}, class:"flex items-center justify-center px-4 py-2 text-sm font-medium text-white rounded-lg bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 focus:outline-none dark:focus:ring-primary-800" %>
            <dialog data-dialog-target="modal" class="backdrop:bg-slate-400 backdrop:opacity-80">
                <%= turbo_frame_tag :modal %>
            </dialog>
          </div>   
        </div>
      </div>

      <%= turbo_frame_tag :users_results, data: {turbo_action: 'advance'} do %>
        <div class="overflow-x-auto">
          <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
              <tr>
                <th scope="col" class="w-1/4 px-5 py-3">
                  <%= sort_link(@q, :full_name, default_order: :desc) do %>
                    FULL NAME
                  <% end %>
                </th>
                <th scope="col" class="w-1/4 px-5 py-3 sm:px-10"><%= sort_link(@q, :site_users_roles, default_order: :desc) %></th>
                <th scope="col" class="w-1/4 px-5 py-3 sm:px-10"><%= sort_link(@q, :country, default_order: :desc) %></th>
                <th scope="col" class="w-1/4 px-5 py-3 sm:px-10">
                    <span class="sr-only">Actions</span>
                </th>
              </tr>
            </thead>
            <tbody id="users">
              <% @users.each do |user| %>
                <%= render partial: "users/index/user_row", locals: {user: user} %>
              <%end%>
            </tbody>
          </table>
        </div>
        <div class="flex justify-end p-2">
          <%== pagy_nav(@pagy) %>  
        </div>
      <%end%>
      
    </div>
  </div>
</div>