config/routes.rb
require "constraints/subdomain_constraint"

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions", invitations: "users/invitations" }
  resources :home
  resources :sites

  constraints(SubdomainConstraint.new) do
    root "sites#show", as: :site_root
    resources :site_users, only: [ :destory ] do
      collection do
        post :invite
      end
    end
    resources :users, only: [ :index, :show, :edit, :update ]
  end

  root "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :set_completed_registration_false
  after_invitation_accepted :set_completed_registration_true

  belongs_to :site, optional: true
  has_many :site_users
  has_one_attached :avatar do |attachable|
    attachable.variant :avatar, resize_to_limit: [ 200, 200 ]
    attachable.variant :thumb, resize_to_limit: [ 50, 50 ]
  end

  validates :first_name, presence: true
  validates :last_name, presence: true

  ransacker :full_name do |parent|
    Arel::Nodes::NamedFunction.new("concat", [
      parent.table[:first_name],
      Arel::Nodes::Quoted.new(" "),
      parent.table[:last_name]
    ])
  end

  def self.ransackable_attributes(auth_object = nil)
    [ "full_name", "first_name", "last_name", "country", "email" ]
  end

  def self.ransackable_associations(auth_object = nil)
    [ "site_users" ]
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name

    "Anonymous"
  end

  def full_address
    "#{address}, #{zip_code}, #{city},"
  end

  private

  def set_completed_registration_false
    self.update(completed_registration: false)
  end

  def set_completed_registration_true
    self.update(completed_registration: true)
  end
end

app/controllers/Users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/Users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  before_action :set_current_site

  def create
    self.resource = invite_resource
    resource_invited = resource.errors.empty?

    yield resource if block_given?

    if resource_invited
      @users = @current_site.users

      if is_flashing_format? && self.resource.invitation_sent_at
        set_flash_message :notice, :send_instructions, email: self.resource.email
      end

      resource.site_users.find_or_create_by(site: @current_site, roles: :member)

      respond_to do |format|
        if self.method(:after_invite_path_for).arity == 1
          location = after_invite_path_for(current_inviter)
        else
          location = after_invite_path_for(current_inviter, resource)
        end

        format.html { respond_with resource, location: location }

        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.prepend("users", partial: "users/index/user_row", locals: { user: resource }),
            turbo_stream.update("flash", partial: "layouts/flash")
          ]
        end
      end
    else
      respond_with(resource)
    end
  end

  # PUT /resource/invitation
  def update
    raw_invitation_token = update_resource_params[:invitation_token]
    self.resource = accept_resource
    invitation_accepted = resource.errors.empty?

    yield resource if block_given?

    if invitation_accepted
      if resource.class.allow_insecure_sign_in_after_accept
        flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
        set_flash_message :notice, flash_message if is_flashing_format?
        resource.after_database_authentication
        sign_in(resource_name, resource)
        redirect_to site_root_url(subdomain: current_user.site_users.first.site.subdomain), allow_other_host: true
      else
        set_flash_message :notice, :updated_not_active if is_flashing_format?
        respond_with resource, location: new_session_path(resource_name)
      end
    else
      resource.invitation_token = raw_invitation_token
      respond_with(resource)
    end
  end
end

app/controllers/Users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/Users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/Users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
    new_site_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/Users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    redirect_to site_root_url(subdomain: current_user.site_users.first.site.subdomain), allow_other_host: true
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # Changed redirect_to for cleaning subdomain
  def respond_to_on_destroy
    respond_to do |format|
      format.all { head :no_content }
      format.any(*navigational_formats) { redirect_to root_url(subdomain: nil), status: Devise.responder.redirect_status, allow_other_host:  true }
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/Users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [ :show, :edit, :update ]
  before_action :set_current_site

  def index
    @q = @current_site.users.order(first_name: :asc).ransack(params[:q])
    @pagy, @users = pagy(@q.result.includes(:site_users), limit: 10)
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User was updated successfully"
      redirect_to user_url(subdomain: @user.site_users.first.site.subdomain), allow_other_host: true
    else
      render edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :phone_number,
                                 :country,
                                 :city,
                                 :zip_code,
                                 :address,
                                 :birthday,
                                 :languages,
                                 :education,
                                 :work_history,
                                 :about_me,
                                 :hobbies,
                                 :skills)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/invitations/edit.html.erb
<h2><%= t "devise.invitations.edit.header" %></h2>

<%= form_for(resource, as: resource_name, url: invitation_path(resource_name), html: { method: :put }) do |f| %>
  <%= render "users/shared/error_messages", resource: resource %>
  <%= f.hidden_field :invitation_token, readonly: true %>

  <% if f.object.class.require_password_on_accepting %>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit t("devise.invitations.edit.submit_button") %>
  </div>
<% end %>

app/views/users/invitations/new.html.erb
<%= turbo_frame_tag :modal do %>
  <div data-action="turbo:submit-end->dialog#submitEnd">
    <div class="flex flex-col items-center justify-center">          
      <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
        <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
          <div class="mb-6 text-2xl font-semibold text-gray-900 dark:text-white">
            <h2><%= t "devise.invitations.new.header" %></h2>
          </div>
          <%= form_for(resource, as: resource_name, url: invitation_path(resource_name), html: { method: :post }) do |f| %>
            <%= render "devise/shared/error_messages", resource: resource %>
            <div class="space-y-4 md:space-y-6">
              <% resource.class.invite_key_fields.each do |field| -%>
                <div class="field">
                  <%= f.label field, class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
                  <%= f.text_field field, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder: 'Email' %>
                </div>
              <% end %>

              <div class="field">
                <%= f.label :first_name, class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
                <%= f.text_field :first_name, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder: 'First name' %>
              </div>

              <div class="field">
                <%= f.label :last_name, class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
                <%= f.text_field :last_name, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder: 'Last name' %>
              </div>

              <div class="actions">
                <%= f.submit t("devise.invitations.new.submit_button"), class:"w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800" %>
              </div>

            </div>
          <% end %>
              <div>
                <button data-action="dialog#close">Cancel</button>
              </div>
        </div>
      </div>
    </div>
  </div>
<% end %>