config/routes.rb
require "constraints/subdomain_constraint"

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions", invitations: "users/invitations" }
  resources :home
  resources :sites

  constraints(SubdomainConstraint.new) do
    root "sites#show", as: :site_root
    resources :site_users, only: [ :destory ] do
      collection do
        post :invite
      end
    end
    resources :users, only: [ :index, :show, :edit, :update ]
  end

  root "home#index"
end

app/models/site.rb
class Site < ApplicationRecord
  has_many :site_users, dependent: :destroy
  has_many :users, through: :site_users
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_current_site, except: [ :new, :create ]
  before_action :set_site, only: [ :show ]
  before_action :authorize_site_user, only: [ :show ]

  def index
    @sites = Site.all
  end

  def show
  end

  def create
    @site = Site.new(site_params)
    if @site.save
      @site.site_users.create!(user: current_user, roles: 0)
      current_user.update(completed_registration: true)
      redirect_to site_root_url(subdomain: @site.subdomain), allow_other_host: true
    end
  end

  private

  def set_site
    @site = @current_site
  end

  def authorize_site_user
    redirect_to(sites_url(subdomain: nil), allow_other_host: true, alert: "You are not a user of this site") unless @site.users.include?(current_user)
  end

  def site_params
    params.require(:site).permit(:name, :subdomain, :background_color, :primary_color)
  end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/index.html.erb
<h1>Sites</h1>
<%= link_to "Logout", destroy_user_session_path, data: { "turbo-method": :delete } %>
<%= link_to 'New', new_site_path %>

<ul>
<% @sites.each do |site| %>
<li><%= link_to site.name, site_root_url(subdomain: site.subdomain) %></li>
<% end %>
</ul>

app/views/sites/new.html.erb
<form action="/sites" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input type="text" name="site[subdomain]" placeholder="www">

  <input type="text" name="site[name]" placeholder="Name">

  <input type="color" name="site[background_color]" placeholder="#fff">

  <input type="color" name="site[primary_color]" placeholder="#fff">

  <button>Create Site</button>
</form>

app/views/sites/show.html.erb
<div style="background-color: <%= @site.background_color %>; color: <%= @site.primary_color %>;">
  <h1><%= @site.name %></h1>
  <p><%= @site.subdomain %></p>
</div>
<div>
  <% @site.site_users.each do |site_user| %>
    <%= site_user.user.email %> 
    <%= site_user.roles %>
    <%= link_to 'Profile', user_url(current_user, subdomain: current_user.site_users.first.site.subdomain) %>
  <% end %>
</div>


<%= link_to "Logout", destroy_user_session_path, data: { "turbo-method": :delete } %>
<%= link_to "Sites", sites_url(subdomain: @site.subdomain) %>
<%= link_to "Users", users_path(subdomain: @site.subdomain) %>